name: 'Godot Export'
description: 'Automatically exports your Godot games.'
author: 'Firebelley'
branding:
  icon: 'box'
  color: 'white'
inputs:
  # required inputs
  godot_executable_download_url:
    description: The download url of the 64 bit Linux Headless Godot executable.
    required: true
  godot_export_templates_download_url:
    description: The url of the export templates corresponding to the Godot executable version.
    required: true
  relative_project_path:
    description: The relative path containing the "project.godot" file.
    required: true

  # optional inputs
  archive_export_output:
    description: If exports should be archived.
    default: false
    required: false
  archive_single_release_output:
    description: If exports that result in single files should be archived.
    default: true
    required: false
  base_version:
    description: The version which new releases start at.
    default: 0.0.1
    required: false
  create_release:
    description: If releases should be automatically created.
    default: true
    required: false
  generate_release_notes:
    description: If release notes should be automatically generated based on commit history.
    default: false
    required: false
  use_preset_export_path:
    description: If set to true, exports will be moved to directory defined in "export_presets.cfg" relative to the root of the Git repository. Prioritized over "relative_export_path".
    default: false
    required: false
  relative_export_path:
    description: If provided, exports will be moved to this directory relative to the root of the Git repository.
    default: ''
    required: false
  update_windows_icons:
    description: If Windows executable icons should be updated with the preset's .ico file.
    default: false
    required: false
  export_debug:
    description: If should export with debugging tools.
    default: false
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
